#!/bin/sh -e

mkdir -p "$1/usr/lib/firmware/amd-ucode"
mkdir -p "$1/usr/lib/firmware/amdgpu"
mkdir -p "$1/usr/lib/firmware/rtl_nic"

cp amd-ucode/microcode_amd_fam19h.bin   "$1/usr/lib/firmware/amd-ucode/"
cp amdgpu/tahiti_*.bin                  "$1/usr/lib/firmware/amdgpu/"
cp rtl_nic/rtl8168g-2.fw                "$1/usr/lib/firmware/rtl_nic/"
