#!/bin/sh -e

if [ -f config ]; then
    echo '>>> using shipped config'
    cp config .config
else
    echo '>>> using x86_64_defconfig'
    make x86_64_defconfig
fi

make olddefconfig

modulesdir="$1/usr/lib/modules/$2"
builddir="$modulesdir/build"

echo "making linux-$2"
make -j8

echo "installing modules..."
make INSTALL_MOD_PATH="$1/usr" modules_install

echo "cleaning up..."
rm -f "$modulesdir/build" "$modulesdir/source"

echo "copying files to build external modules..."
install -Dt "$builddir"                 -m644 .config Makefile Module.symvers System.map vmlinux
install -Dt "$builddir/arch/x86"        -m644 arch/x86/Makefile
install -Dt "$builddir/arch/x86/kernel" -m644 arch/x86/kernel/asm-offsets.s
install -Dt "$builddir/kernel"          -m644 kernel/Makefile
install -Dt "$builddir/drivers/md"      -m644 drivers/md/*.h
install -Dt "$builddir/net/mac80211"    -m644 net/mac80211/*.h
install -Dt "$builddir/tools/objtool"         tools/objtool/objtool

cp -a scripts          "$builddir/scripts"
cp -a include          "$builddir/include"
cp -a arch/x86/include "$builddir/arch/x86/include"

find . -name "Kconfig*" -exec install -Dm644 {} "$builddir/{}" \;

chmod -Rc u=rwX,go=rX "$1"

echo "removing cruft..."
rm   -r "$builddir/Documentation"
find -L "$builddir" -type l             -exec rm -rf {} +
find    "$builddir" -type f -name "*.o" -exec rm -rf {} +

echo "laying trap..."
mkdir -p "$1/usr/src"
ln -sv "/usr/lib/modules/$2/build" "$1/usr/src/linux"

echo "installing kernel..."
mkdir -p "$1/boot"
install -Dm644 "arch/x86/boot/bzImage" "$1/boot/vmlinuz-$2"
install -Dm644 "System.map"            "$1/boot/System.map-$2"
install -Dm644 ".config"               "$1/boot/config-$2"
